#include "voxel.slangh"

#define MAX_RAY_STEPS 256

struct Ray {
    float3 origin;
    float3 direction;
}

struct AABB {
    int3 pos;
    uint3 size;
};

struct AABBIntersection {
    bool hit;
    float near;
    float far;
    float3 t0;
    float3 t1;
};

struct TraceResult {
    bool hit;
    int3 position;
    float depth;
    float3 normal;
    Voxel voxel;
}

struct DDAState {
    int3 pos;
    float3 delta;
    int3 rayStep;
    float3 sideDist;
    bool3 mask;
    float entryDepth;
};

float Min3(float3 v) {
    return min(v.x, min(v.y, v.z));
}

float Max3(float3 v) {
    return max(v.x, max(v.y, v.z));
}

bool3 MinMask(float3 v) {
    float m = min(v.x, min(v.y, v.z));
    return v <= m;
}

DDAState InitDDA(Ray ray, float cellSize, float3 gridOrigin, float startDepth, int3 startCell, bool3 entryMask) {
    DDAState s;

    s.rayStep = int3(sign(ray.direction));
    s.pos = startCell;

    // Avoid inf for zero-direction components.
    s.delta = select(
        abs(ray.direction) < 1e-8,
        float3(1e30),
        abs(cellSize / ray.direction)
    );

     float3 nextBoundary = select(
        s.rayStep == 0,
        float3(float.maxValue),
        select(
            s.rayStep > 0,
            float3(s.pos + 1),
            float3(s.pos)
        )
    );

    float3 boundaryPosition = gridOrigin + nextBoundary * cellSize;

    s.sideDist = (boundaryPosition - ray.origin) / ray.direction;

    // Explicitly disable zero-direction axes.
    s.sideDist = max(s.sideDist, float3(s.rayStep == 0) * float.maxValue);
    s.sideDist = max(s.sideDist, startDepth);

    s.mask = entryMask;
    s.entryDepth = startDepth;

    return s;
}

void AdvanceDDA(inout DDAState s) {
    s.mask = MinMask(s.sideDist);
    s.pos += int3(s.mask) * s.rayStep;
    s.entryDepth = Min3(s.sideDist);
    s.sideDist += float3(s.mask) * s.delta;
}


float3 DDAEntryNormal(DDAState s) {
    float3 normal = -float3(s.rayStep) * float3(s.mask);
    float len = length(normal);
    if (len > 0.0)
        return normal / len;
    return float3(0.0);
}

bool NodeIsVoxel(StructuredBuffer<ContreeNode> nodes, uint nodeIndex, uint childIndex) {
    return bool((nodes[nodeIndex].isVoxelMask >> childIndex) & 1ull);
}


uint NodeChild(StructuredBuffer<ContreeNode> nodes,uint nodeIndex,uint childIndex) {
    return nodes[nodeIndex].child_nodes[childIndex];
}

TraceResult TraceWorld(Ray ray, float maxDepth, StructuredBuffer<ContreeNode> contreeNodes, StructuredBuffer<Chunk> chunks, StructuredBuffer<ChunkPositionsHeader> chunkPositionsHeader, StructuredBuffer<uint32_t> chunkPositions) {
    TraceResult result;

    result.hit = false;
    result.position = int3(0);
    result.depth = float.maxValue;
    result.normal = ray.direction;
    result.voxel = Voxel(0);

    ChunkPositionsHeader header = chunkPositionsHeader[0];

    const float chunkSize = float(Chunk.CHUNK_WIDTH);

    int3 regionPosition = header.position;
    uint3 regionSize = header.size;
    uint regionWidth = regionSize.x;
    uint regionArea = regionSize.x * regionSize.y;

    AABB boundingBox = AABB(
        regionPosition * Chunk.CHUNK_WIDTH,
        regionSize * Chunk.CHUNK_WIDTH
    );

    AABBIntersection intersection = IntersectAABB(ray, boundingBox);

    if (!intersection.hit)
        return result;

    float3 regionOrigin = float3(regionPosition) * chunkSize;

    float3 tEnter = min(intersection.t0, intersection.t1);

    bool3 entryMask = bool3(
        abs(tEnter.x - intersection.near) <= 1e-5,
        abs(tEnter.y - intersection.near) <= 1e-5,
        abs(tEnter.z - intersection.near) <= 1e-5
    );

    float3 entryPosition =
        ray.origin +
        ray.direction *
        (intersection.near + 1e-4);

    int3 rootCell =
        int3(floor(
            (entryPosition - regionOrigin) /
            chunkSize
        ));

    rootCell = clamp(
        rootCell,
        int3(0),
        int3(regionSize) - 1
    );

    DDAState ddaState =
        InitDDA(
            ray,
            chunkSize,
            regionOrigin,
            intersection.near,
            rootCell,
            entryMask
        );

    int maxSteps =
        int(
            regionSize.x +
            regionSize.y +
            regionSize.z
        );

    for (int i = 0; i < maxSteps; ++i) {
        if (any(ddaState.pos < 0) || any(ddaState.pos >= int3(regionSize))) break;
        if (maxDepth >= 0.0 && ddaState.entryDepth > maxDepth) break;

        int3 localChunkPos = ddaState.pos;

        uint chunkIndex =
            chunkPositions[
                uint(localChunkPos.x) +
                uint(localChunkPos.y) * regionWidth +
                uint(localChunkPos.z) * regionArea
            ];

        if (chunkIndex != POINTER_EMPTY) {
            Chunk chunk = chunks[chunkIndex];

            TraceResult chunkResult =
                TraceChunk(
                    chunk,
                    ray,
                    maxDepth,
                    ddaState.entryDepth,
                    ddaState.mask,
                    contreeNodes
                );

            if (chunkResult.hit) {
                result.hit = true;
                result.depth = chunkResult.depth;
                result.voxel = chunkResult.voxel;
                result.normal = chunkResult.normal;

                result.position =
                    chunkResult.position +
                    chunk.position *
                    Chunk.CHUNK_WIDTH;

                return result;
            }
        }

        AdvanceDDA(ddaState);
    }

    return result;
}

TraceResult TraceChunk(Chunk chunk, Ray ray, float maxDepth, float startDepth, bool3 entryMask, StructuredBuffer<ContreeNode> contreeNodes) {
    TraceResult result;

    result.hit = false;
    result.position = int3(0);
    result.depth = float.maxValue;
    result.normal = ray.direction;
    result.voxel = Voxel(0);

    const int N = int(ContreeNode.NODE_WIDTH);
    const int MAX_DEPTH = int(ContreeNode.MAX_DEPTH);
    const float chunkWidth = float(Chunk.CHUNK_WIDTH);

    Ray localRay = ray;
    localRay.origin -= float3(chunk.position) * chunkWidth;

    DDAState rootDDA;
    DDAState childDDA;
    DDAState leafDDA;

    uint rootNode;
    uint childNode;
    uint leafNode;

    int3 rootOrigin;
    int3 childOrigin;
    int3 leafOrigin;
    int stackPosition = 0;

    float rootCellSize = chunkWidth / float(N);
    float3 chunkLocalEntry = localRay.origin + localRay.direction * startDepth;
    float3 rootClassifyPosition = chunkLocalEntry + localRay.direction * 1e-4;
    int3 rootCell =
        clamp(
            int3(floor(
                rootClassifyPosition /
                rootCellSize
            )),
            int3(0),
            int3(N - 1)
        );

    rootDDA =
        InitDDA(
            localRay,
            rootCellSize,
            float3(0.0),
            startDepth,
            rootCell,
            entryMask
        );

    rootNode = chunk.contree_node;
    rootOrigin = int3(0);

    for (int iteration = 0; iteration < MAX_RAY_STEPS; ++iteration) {

        DDAState st;
        uint nodeIdx;
        int3 nodeOrigin;

        if (stackPosition == 0) {
            st = rootDDA;
            nodeIdx = rootNode;
            nodeOrigin = rootOrigin;
        }
        else if (stackPosition == 1) {
            st = childDDA;
            nodeIdx = childNode;
            nodeOrigin = childOrigin;
        }
        else {
            st = leafDDA;
            nodeIdx = leafNode;
            nodeOrigin = leafOrigin;
        }

        float levelCellSize;

        if (stackPosition == 0)
            levelCellSize = 16.0;
        else if (stackPosition == 1)
            levelCellSize = 4.0;
        else
            levelCellSize = 1.0;

        if (any(st.pos < 0) || any(st.pos >= int3(N))) {
            if (stackPosition == 0)
                break;

            stackPosition--;

            if (stackPosition == 0) {
                AdvanceDDA(rootDDA);
            }
            else if (stackPosition == 1) {
                AdvanceDDA(childDDA);
            }

            continue;
        }

        uint childIndex =
            uint(
                st.pos.x +
                st.pos.y * N +
                st.pos.z * N * N
            );

        if (NodeIsVoxel(contreeNodes, nodeIdx, childIndex)) {
            uint rawVoxel = NodeChild(contreeNodes, nodeIdx, childIndex);
            Voxel v = (Voxel)rawVoxel;

            if (v.solid()) {
                float hitDepth = st.entryDepth;
                if (maxDepth >= 0.0 && hitDepth > maxDepth) break;

                result.normal = -float3(st.rayStep) * float3(st.mask);

                float3 hitPosition =
                    localRay.origin +
                    localRay.direction * hitDepth -
                    result.normal * 0.5;

                int3 voxelPosition = int3(floor(hitPosition));

                result.hit = true;
                result.voxel = v;
                result.position = voxelPosition;
                result.depth = hitDepth;
                

                return result;
            }

            AdvanceDDA(st);

            if (stackPosition == 0)
                rootDDA = st;
            else if (stackPosition == 1)
                childDDA = st;
            else
                leafDDA = st;

            continue;
        }

        if (stackPosition + 1 >= MAX_DEPTH) {
            AdvanceDDA(st);
            leafDDA = st;
            continue;
        }

        uint childPtr = NodeChild(contreeNodes, nodeIdx, childIndex);
        if (childPtr == POINTER_EMPTY) {
            AdvanceDDA(st);
            if (stackPosition == 0)
                rootDDA = st;
            else if (stackPosition == 1)
                childDDA = st;
            else
                leafDDA = st;
            continue;
        }

        float childStartDepth = st.entryDepth;
        bool3 childEntryMask = st.mask;
        int3 childOriginNew = nodeOrigin * N + st.pos;
        float3 childOriginWorld = float3(childOriginNew) * levelCellSize;
        float childCellSize = levelCellSize / float(N);

        float3 entryLocal = (localRay.origin + localRay.direction * st.entryDepth - childOriginWorld) / childCellSize;

        int3 childStartCell =
            clamp(
                int3(floor(entryLocal)),
                int3(0),
                int3(N - 1)
            );

        DDAState newChildDDA =
            InitDDA(
                localRay,
                childCellSize,
                childOriginWorld,
                childStartDepth,
                childStartCell,
                childEntryMask
            );

        if (stackPosition == 0) {
            childDDA = newChildDDA;
            childNode = childPtr;
            childOrigin = childOriginNew;
        }
        else {
            leafDDA = newChildDDA;
            leafNode = childPtr;
            leafOrigin = childOriginNew;
        }
        stackPosition++;
    }
    return result;
}

AABBIntersection IntersectAABB(Ray ray, AABB aabb) {
    float3 invDir = 1.0 / ray.direction;

    float3 t0 = (float3(aabb.pos) - ray.origin) * invDir;
    float3 t1 = (float3(aabb.pos + aabb.size) - ray.origin) * invDir;

    float3 tMin3 = min(t0, t1);
    float3 tMax3 = max(t0, t1);

    float tmin = Max3(tMin3);
    float tmax = Min3(tMax3);

    AABBIntersection result;
    result.near = max(tmin, 0.0);
    result.far = tmax;
    result.hit = tmax >= result.near;
    result.t0 = t0;
    result.t1 = t1;
    return result;
}

float2 GetNDC( int2 pos, int2 size) {
    float2 uv = (float2(pos) + 0.5) / float2(size);
    float2 ndc = uv * 2.0 - 1.0;
    ndc.y = -ndc.y;
    float aspect = float(size.x) / float(size.y);
    ndc.x *= aspect;
    return ndc;
}