#ifndef VOXEL_SLANGH
#define VOXEL_SLANGH

static const uint32_t POINTER_EMPTY = 0xFFFFFFFF;

struct Voxel {
    enum Type : uint {
        Regular = 0,
        Emissive = 1
    };

    static const uint COLORCHANNEL = 0x1Fu;
    static const uint SOLID = 0x8000u;

    uint data = 0;

    uint r() { return data & COLORCHANNEL; }
    uint g() { return (data >> 5) & COLORCHANNEL; }
    uint b() { return (data >> 10) & COLORCHANNEL; }

    bool solid() { return (data & SOLID) != 0u; }
    uint payload() { return (data >> 16) & 0x1Fu; }
    Type type() { return Type((data >> 21) & 0x03u); }

    float3 color() {
        return float3(float(r()), float(g()), float(b())) / 31.0f;
    }

    [mutating]
    void set_r(uint v) {
        data = (data & ~0x001Fu) | (v & 0x1Fu);
    }

    [mutating]
    void set_g(uint v) {
        data = (data & ~0x03E0u) | ((v & 0x1Fu) << 5);
    }

    [mutating]
    void set_b(uint v) {
        data = (data & ~0x7C00u) | ((v & 0x1Fu) << 10);
    }

    [mutating]
    void set_rgb(uint r, uint g, uint b) {
        set_r(r);
        set_g(g);
        set_b(b);
    }

    [mutating]
    void set_solid(bool v) {
        if (v) data |= SOLID;
        else data &= ~SOLID;
    }

    [mutating]
    void set_payload(uint v) {
        data = (data & ~(0x1Fu << 16)) | ((v & 0x1Fu) << 16);
    }

    [mutating]
    void set_type(Type v) {
        data = (data & ~(0x03u << 21)) | ((uint(v) & 0x03u) << 21);
    }
};

struct ContreeHeader {
    uint64_t isVoxelMask;
    uint64_t isSolidMask;
    bool is_voxel(uint8_t index) {
        return bool((isVoxelMask >> index) & 1ull);
    }
    bool is_solid(uint8_t index) {
        return bool((isSolidMask >> index) & 1ull);
    }
};

struct ContreeData {
    uint32_t child_nodes[ContreeNode::NODE_WIDTH * ContreeNode::NODE_WIDTH * ContreeNode::NODE_WIDTH];

    Voxel get_voxel(uint8_t index) {
        return (Voxel)child_nodes[index];
    }

    uint32_t get_ptr(uint8_t index) {
        return child_nodes[index];
    }
};

struct ContreeNode {
    static const uint8_t NODE_WIDTH = 4;
    static const uint8_t MAX_DEPTH = 3;
}

struct Chunk {
    static const uint8_t WIDTH = 64;
    int3 position;
    uint32_t contree_node;
};

struct ChunkPositionsHeader {
    int3 position;
    uint3 size;
    uint32_t get_size(void) { return size.x * size.y * size.z; }
};

#endif