#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 16, local_size_y = 16) in;
layout(set=1, binding = 0, rgba8) uniform writeonly image2D destImage;

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imgSize = imageSize(destImage);
    if (pos.x >= imgSize.x || pos.y >= imgSize.y) return; // dont do pixels that are outside of the texture

    vec3 color = vec3(float(pos.x)/imgSize.x, float(pos.y)/imgSize.y, 0.0);
    
    imageStore(destImage, pos, vec4(color.bgr, 1.0));
}